---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'git'
    - 'golang-go'
    - 'make'

- name: git clone
  git:
    repo: "{{ govpn__git }}"
    dest: "/srv/govpn"

- name: Check install version
  shell: /usr/local/bin/govpn-server -version | awk '{ print $3 }'
  register: govpn__version_install_raw
  check_mode: no
  changed_when: False

- name: Check git version
  shell: cat /srv/govpn/VERSION | awk '{ print $0 }'
  register: govpn__version_git_raw
  check_mode: no
  changed_when: False

- name: set govpn__version_{git,install}
  set_fact:
    govpn__version_install: "{{ govpn__version_install_raw.stdout }}"
    govpn__version_git: "{{ govpn__version_git_raw.stdout }}"

- name: make all
  make:
    chdir: /srv/govpn
    target: all
  when: govpn__version_git != govpn__version_install

- name: Copy files
  copy:
    remote_src: True
    src: "/srv/govpn/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    group: root
    owner: root
  with_flattened:
    - 'govpn-client'
    - 'govpn-server'
    - 'govpn-verifier'
  when: govpn__version_git != govpn__version_install

- name: Remove old files
  file:
    path: "/srv/govpn/{{item}}"
    state: absent
  with_flattened:
    - 'govpn-client'
    - 'govpn-server'
    - 'govpn-verifier'
  when: govpn__version_git != govpn__version_install

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
